export const SAVE_NAME = 'SAVE_NAME';

export const REQUIRE_GRAVATAR_SUCCESS = 'REQUIRE_GRAVATAR_SUCCESS';

export const SAVE_SCORE = 'SAVE_SCORE';

export const FEEDBACK_SCORE = 'FEEDBACK_SCORE';

export const RESET_SCORE = 'RESET_SCORE';
